gmail_username: ''
gmail_password: '' 
clients:
  default:
    menus: 
    access:
      all_except: []
    carriers:
    - :aus_post
    - :aus_post_bus
    - :temando
carriers:
  aus_post:
    public: true
    description: Australia Post
    service: true
    legacy_name: AusPost
  aus_post_bus:
    public: true
    description: Australia Post (with Shopify Real-time carrier shipping)
    service: true
    legacy_name: AusPostBus
  temando:
    public: true
    description: Temando
    service: true
    legacy_name: Temando    
